spring:
  applicaion:
    name: study

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #rabbitMQ
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #消费者端配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
      direct:
        acknowledge-mode: manual

  #redis
  redis:
    host: 127.0.0.1
    port: 6379


server:
  port: 8083




#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





